nxhack/openwrt-node-packages

- node-serialport/Makefile
- node/patches/v4.x/009-powerpc_musl_support.patch
- node/patches/v6.x/009-powerpc_musl_support.patch
- node/patches/v8.x/009-powerpc_musl_support.patch
> node: modify powerpc support

- node/Makefile
- node/patches/v8.x-host/001-hardfloat.patch
- node/patches/v8.x-host/002-addr_info.patch
- node/patches/v8.x-host/003-path.patch
- node/patches/v8.x-host/004-execinfo_h.patch
- node/patches/v8.x-host/009-powerpc32_musl_support.patch
- node/patches/v8.x-host/010-execvp-arg-list-too-long.patch
- node/patches/v8.x-host/011-gyp-force-link-command-to-use-CXX.patch
- node/patches/v8.x-host/012-changing-default-npm-settings.patch
- node/patches/v8.x-host/014-npm_cleanup_tmpdir.patch
- node/patches/v8.x/004-node_crypto-remove-std.patch
addresse the issue of v8.10.0 node_crypto definitions of isnan and isinf.
> node: address v8.10.0 gcc5 isuse

- node/Makefile
- node/patches/v10.x/003-path.patch
- node/patches/v10.x/999-fix-mksnapshot_host_build.patch
- node/patches/v11.x/999-fix-mksnapshot_host_build.patch
- node/patches/v6.x/999-fix-mksnapshot_host_build.patch
- node/patches/v8.x/999-fix-mksnapshot_host_build.patch
I was inspired by this website: https://rahulrav.svbtle.com/devtools-adventures-with-an-omega2pro
> node: enable snapshot for chrome devtools

- node/patches/v12.x/999-v8_this_build_method_will_be_deprecated.patch
> node: fix x86_64 patch

- node-red/Makefile
- node-red/files/node-red.conf
- node-red/files/node-red.init
Maintainer: @nxhack 
Compile tested: Turris Omnia (TOS5), OpenWrt master
Run tested: Turris Omnia (TOS5), OpenWrt master
Description:
This PR adds basic init script and config file.
> node-red: add init script and simple config

- node-modclean/Makefile
- node-zigbee2mqtt/Makefile
- node-zigbee2mqtt/files/zigbee2mqtt.init
Ref : https://github.com/nxhack/openwrt-node-packages/issues/1080#issuecomment-986293157
> [21.02] node-zigbee2mqtt: NODE_PATH explicitly set & Reduced size

- node-modclean/Makefile
- node-zigbee2mqtt/Makefile
- node-zigbee2mqtt/files/zigbee2mqtt.init
Ref: https://github.com/nxhack/openwrt-node-packages/issues/1080#issuecomment-986293157
> [19.07] node-zigbee2mqtt: NODE_PATH explicitly set & Reduced size

- node-uglify-js/Makefile
(cherry picked from commit 01d66b0ea4e6c7bd8bd63dac2a7570765ae91dfd)
> node-uglify-js: add exec permission

- node-homebridge/files/homebridge.init
(cherry picked from commit 477ff78414fed99fb9ca845a37fd074d6da3f35f)
> node-homebridge: add HOME env

- node-homebridge/files/homebridge.init
(cherry picked from commit 730e4c7f3038a81f7a480fa9e8e062f0ec9c1d27)
> node-homebridge: change HOME env

- node-gulp/patches/999-npm_fix_git_depends.patch
- node-socket.io/patches/999-npm_fix_git_depends.patch
(cherry picked from commit 1f6f1e373ad58cf86d4eba989be36028aca8c945)
> [22.03] Avoid using git protocol

- node-gulp/patches/999-npm_fix_git_depends.patch
- node-socket.io/patches/999-npm_fix_git_depends.patch
(cherry picked from commit 1f6f1e373ad58cf86d4eba989be36028aca8c945)
> [21.02] Avoid using git protocol

- node-zigbee2mqtt/files/zigbee2mqtt.init
(cherry picked from commit af05f3eae3316fc720c25249dab52f60df2c0329)
> [22.03] node-zigbee2mqtt: workaround in case it cannot be stopped

- node-zigbee2mqtt/files/zigbee2mqtt.init
(cherry picked from commit af05f3eae3316fc720c25249dab52f60df2c0329)
> [21.02] node-zigbee2mqtt: workaround in case it cannot be stopped

- node-ejdb2_node/Makefile
(cherry picked from commit 5aef275050c273cb7e7f6394ec274a2308a58667)
> [22.03] node-ejdb2_node: Temporarily mark @BROKEN

- node-ejdb2_node/Makefile
(cherry picked from commit 5aef275050c273cb7e7f6394ec274a2308a58667)
> [21.02] node-ejdb2_node: Temporarily mark @BROKEN

- node/Makefile
ref: https://github.com/nxhack/openwrt-node-packages/pull/1390
Signed-off-by: Hirokazu MORIKAWA <morikw2@gmail.com>
(cherry picked from commit c6922a8656e1c75dc2960abe54272a0ca1e7e2c0)
> [22.03] node: Allow change versions on host package

- node/Makefile
ref: https://github.com/nxhack/openwrt-node-packages/pull/1390
Signed-off-by: Hirokazu MORIKAWA <morikw2@gmail.com>
> [21.02] node: Allow change versions on host package

- node-homebridge/Makefile
(cherry picked from commit e297150229e68229bd800d4eb272a60a16d19de3)
> [22.03] node-homebridge: support scope

- node-homebridge-config-ui-x/Makefile
- node-homebridge-config-ui-x/files/org.freedesktop.Avahi.AddressResolver.xml
- node-homebridge-config-ui-x/files/org.freedesktop.Avahi.DomainBrowser.xml
- node-homebridge-config-ui-x/files/org.freedesktop.Avahi.EntryGroup.xml
- node-homebridge-config-ui-x/files/org.freedesktop.Avahi.HostNameResolver.xml
- node-homebridge-config-ui-x/files/org.freedesktop.Avahi.RecordBrowser.xml
- node-homebridge-config-ui-x/files/org.freedesktop.Avahi.Server.xml
- node-homebridge-config-ui-x/files/org.freedesktop.Avahi.ServiceBrowser.xml
- node-homebridge-config-ui-x/files/org.freedesktop.Avahi.ServiceResolver.xml
- node-homebridge-config-ui-x/files/org.freedesktop.Avahi.ServiceTypeBrowser.xml
(cherry picked from commit 5321c57d9695a3549af09742d9dbec30de2b48f3)
> node-homebridge-config-ui-x: fix avahi dbus issue

- node/Makefile
(cherry picked from commit 08d8bac14e230c4721502c07535de94106927980)
> node: use J

- node-aws-crt/patches/001-modify_compile_options.patch
(cherry picked from commit f37765c8c67528a371e461b530bc0c156f6b66f7)
> node-aws-crt: Solves async processing issue

- node-zigbee2mqtt/Makefile
(cherry picked from commit 0fe18e543eb4a9185786fced8907e60fb8578278)
> [23.05] Upgrade zigbee2mqtt to 1.31.2

- node-zigbee2mqtt/Makefile
(cherry picked from commit 0fe18e543eb4a9185786fced8907e60fb8578278)
> [22.03] Upgrade zigbee2mqtt to 1.31.2

- node/Makefile
(cherry picked from commit 5c3ba60e4ab65e1ba9d72bbe1dab7bcde251969a)
> node: Explicitly specify rm command

- node/Makefile
(cherry picked from commit 350dabdb6226d4c600ba11e36eac9f16e9c5ca02)
> [23.05] node: add ABI_VERSION

- node-homebridge-config-ui-x/files/openwrt.js
(cherry picked from commit 3447626861112d6980e531434c44e2a01c51d2d9)
> [23.05] node-homebridge-config-ui-x: fix getPidOfPort

- node-lambda/Makefile
- node-lambda/patches/000-remove_depends.patch
(cherry picked from commit 7b8aa2dff874024327e00077b3edab69a77af2aa)
> node-lambda: use node-aws-sdk package

- node-zwave-js-ui-bundle/Makefile
(cherry picked from commit 0329acde6dcb8cc2feeef84929f05435524759f6)
> [23.05] node-zwave-js-ui-bundle: Add a comment

- node-zwave-js-ui-bundle/Makefile
(cherry picked from commit 0329acde6dcb8cc2feeef84929f05435524759f6)
> [22.03] node-zwave-js-ui-bundle: Add a comment

- node-homebridge-xiaomi-roborock-vacuum/Makefile
(cherry picked from commit 615b89ae90cee258666992cf2fe7edc4e9b3b362)
> [23.05] node-homebridge-xiaomi-roborock-vacuum: add new package

- node-ffi-napi/Makefile
- node-homebridge-xiaomi-roborock-vacuum/Makefile
(cherry picked from commit 615b89ae90cee258666992cf2fe7edc4e9b3b362)
> [22.03] node-homebridge-xiaomi-roborock-vacuum: add new package

- node-homebridge-miot/Makefile
(cherry picked from commit 3468b45f147bc3fad20a617866ba4783a604da2e)
> [23.05] node-homebridge-miot: modify TITLE

- node-homebridge-miot/Makefile
(cherry picked from commit 3468b45f147bc3fad20a617866ba4783a604da2e)
> [22.03] node-homebridge-miot: modify TITLE

- node-aws-crt/patches/999-fix_axios.patch
(cherry picked from commit 006958480bca5214d131a85ea9038d15b79fe444)
> node-aws-crt: fix axios version
