node/patches/v8.x/010-execvp-arg-list-too-long.patch, node/patches/v8.x/011-gyp-force-link-command-to-use-CXX.patch, node/patches/v8.x/012-changing-default-npm-settings.patch
Pull request for the following patches :
* **010-execvp-arg-list-too-long.patch**
needed to finalize HOST build on systems running gcc v6 series
* **011-gyp-force-link-command-to-use-CXX.patch**
forcing CXX link with GYP
* **012-changing-default-npm-settings.patch**
using **loglevel** to `info` and **strict-ssl** to `false` for NPM
=> node8 : refreshing patches for HOST build with gcc v6 series

node/Makefile
Since release v8.3.0, the HOST build becomes unnecessary when cross-build. Thanks! @artynet
=> node: update to v8.4.0

node-leveldown/Makefile, node-serialport-list/Makefile, node-serialport-repl/Makefile, node-serialport-terminal/Makefile
"npm_config_build_from_source=true" seems not to be effective.
=> support x86_64

node/Makefile, node/patches/v10.x/999-fix_mksnapshot_host_build.patch, node/patches/v11.x/999-fix_mksnapshot_host_build.patch, node/patches/v6.x/999-fix_mksnapshot_host_build.patch, node/patches/v8.x/999-fix_mksnapshot_host_build.patch
64bit CPU support (exclude x86-64)
aarch64 work fine. (w small-icu and system-icu)
=> node: support snapshot

node/patches/v8.x/013-npm-unsafe-override-for-global-install.patch, node/patches/v9.x/013-npm-unsafe-override-for-global-install.patch
As in subject, npm clashes with OpenWrt when trying to install a package globally. The issue is described here :
https://github.com/nodejs/node-gyp/issues/454
the patches override the default setting of **unsafe-perm** entry.
=> npm: allowing installation of global modules overriding the default setting for root

node-red-admin/Makefile, npm-package.mk
Maintainer: me
Compile tested: Turris Omnia (TOS5), OpenWrt master
Run tested: Turris Omnia (TS5), OpenWrt master
Description:
This PR adds new package node-red-admin which is CLI tool for node-red administration.
It also contains **npm-package.mk** which could simplify the packaging of npm packages  in the future .
=> node-red-admin: add new package and npm-package.mk

node-bleacon/Makefile, node-bluetooth-hci-socket/Makefile, node-eddystone-beacon/Makefile, node-hid/Makefile, node-usb/Makefile
Recently in OpenWrt packages repository, there was removed package
libudev-fbsd in favor of libudev-zero which provides libudev.
Cross-reference: https://github.com/openwrt/packages/pull/13720
It was not compile neither run tested.
=> treewide: change dependency from libudev-fbsd to libudev

node-zigbee2mqtt/Makefile
on devices with openwrt, there is often little memory and it is important to use it usefully.
Deletes large files that are not used for zigbee2mqtt operation
Perhaps this is not the best solution, I will be glad to your advice
=> reduce the size of the collected package and the number of files.

node-modclean/Makefile, node-zigbee2mqtt/Makefile, node-zigbee2mqtt/files/zigbee2mqtt.init
Ref: https://github.com/nxhack/openwrt-node-packages/issues/1080#issuecomment-986293157
=> node-zigbee2mqtt: NODE_PATH explicitly set & Reduced size

node-zigbee2mqtt/Makefile, node-zigbee2mqtt/files/configuration.yaml, node-zigbee2mqtt/files/zigbee2mqtt.init
Notable change:
* Changed location location of configuration.yaml from /opt/zigbee2mqtt/data/ to /etc/zigbee2mqtt.
If you reinstall node-zigbee2mqtt, it will keep configuration.yaml.
* Changed location of log from /opt/zigbee2mqtt/data/log to /tmp/log/zigbee2mqtt.
=> node-zigbee2mqtt: Changed the handling of configuration.yaml

node-zigbee2mqtt/Makefile, node-zigbee2mqtt/files/configuration.yaml, node-zigbee2mqtt/files/zigbee2mqtt.init
Notable change:
* Changed location of configuration.yaml from /opt/zigbee2mqtt/data/ to /etc/zigbee2mqtt.
If you reinstall node-zigbee2mqtt, it will keep configuration.yaml.
* Changed location of log from /opt/zigbee2mqtt/data/log to /tmp/log/zigbee2mqtt.
Signed-off-by: Hirokazu MORIKAWA <morikw2@gmail.com>
=> [19.07] node-zigbee2mqtt: Changed the handling of configuration.yaml

node-red/Makefile
(cherry picked from commit 79417443c44a121982187b222d27af722bc6d735)
=> node-red: bump to 2.2.2

node-sqlite3/Makefile
Updates the description for node-sqlite3 using the description copied from [node-sqlite3's Git repo](https://github.com/TryGhost/node-sqlite3)
The previous description for node-sqlite3 was actually from [node-serialport](https://github.com/serialport/node-serialport).
=> node-sqlite3: fix incorrect package description

node-homebridge/Makefile
(cherry picked from commit e297150229e68229bd800d4eb272a60a16d19de3)
=> [21.02] node-homebridge: support scope

node/Makefile
Install the official nodejs binary package as HOSTPKG.
Reduce build time for host package.
This change was suggested by @artynet
https://github.com/nxhack/openwrt-node-packages/issues/1547
=> node: Use binary package as HOSTPKG

node/Makefile
Install the official nodejs binary package as HOSTPKG
Reduce build time for host package.
This change was suggested by @artynet
https://github.com/nxhack/openwrt-node-packages/issues/1547
fix: OpenWrt 21.02 HOST_OS_LINUX is not present 
Signed-off-by: Hirokazu MORIKAWA <morikw2@gmail.com>
(cherry picked from commit https://github.com/nxhack/openwrt-node-packages/commit/1767ca69f152a9c10115ab6eaac8aea7a0676319)
=> [21.02] node: Use binary package as HOSTPKG

node-bluetooth-hci-socket/Makefile
(cherry picked from commit 8cb170b78cada5b279cd90d9a99a6afdc52c674a)
=> node-bluetooth-hci-socket: add depend bluez-libs

node-bluetooth-hci-socket/Makefile
(cherry picked from commit 8cb170b78cada5b279cd90d9a99a6afdc52c674a)
=> [22.03] node-bluetooth-hci-socket: add depend bluez-libs

node-bluetooth-hci-socket/Makefile
(cherry picked from commit 8cb170b78cada5b279cd90d9a99a6afdc52c674a)
=> [21.02] node-bluetooth-hci-socket: add depend bluez-libs

node-zeromq/Makefile, node-zeromq/patches/001-modify_compile_options.patch
(cherry picked from commit 8d5602d6365c60c45991d073e50c784924bcf407)
=> [23.05] node-zeromq: 0MQ version 4.3.5 stable

node-zeromq/Makefile, node-zeromq/patches/001-modify_compile_options.patch
(cherry picked from commit 8d5602d6365c60c45991d073e50c784924bcf407)
=> [22.03] node-zeromq: 0MQ version 4.3.5 stable

node-homebridge-config-ui-x/files/openwrt.js
(cherry picked from commit 3447626861112d6980e531434c44e2a01c51d2d9)
=> [22.03] node-homebridge-config-ui-x: fix getPidOfPort

node-zeromq/Makefile
(cherry picked from commit f9b74ebf2e0170142f95e368310cfd39c331720c)
=> [22.03] node-zeromq: add host depends node-gyp

node/Makefile
(cherry picked from commit d928bfa5e621184f5bbf44e19b675c69ef49dac7)
=> [24.10] node: support riscv64 Banana Pi BPI-RV2 RISC-V

node-leveldown/Makefile
(cherry picked from commit a6bad0f65254816c90360279c0656b8fd09c710f)
=> [24.10] node-leveldown: @!riscv64

node-leveldown/Makefile
(cherry picked from commit a6bad0f65254816c90360279c0656b8fd09c710f)
=> [23.05] node-leveldown: @!riscv64

node-classic-level/Makefile, node-classic-level/patches/999-support_riscv64.patch
(cherry picked from commit 870aef26f55d7e543d7a8c144ff465a66486cc24)
=> [24.10] node-classic-level: support riscv64
